server:
  port: 8901

spring:
  application:
    name: hello-spring-security-oauth2
  datasource:
    url: jdbc:mysql://192.168.31.3:20041/oauth2_db01  # 替换为你的数据库名称
    username: mysql  # 替换为你的数据库用户名
    password: 12345678  # 替换为你的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver  # 使用 MySQL 8.x 驱动
  jpa:
    hibernate:
      ddl-auto: update  # 自动更新数据库模式（也可以是 create、validate、none）
    show-sql: true  # 是否显示 SQL 语句
    properties:
      hibernate:
        format_sql: true  # 格式化 SQL 语句输出
  # 配置 HikariCP 数据源连接池
  hikari:
    pool-name: MyHikariCP
    maximum-pool-size: 10
    minimum-idle: 5
    connection-timeout: 20000
    idle-timeout: 30000
    max-lifetime: 1800000
  data:
    redis:
      host: 192.168.31.3
      port: 6379
      database: 0
jwt:
  rsa:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApowXG4ADYqm9A/IqANSBJ74A64+dUtaofyqqCxhlxuJkZtzH0Q5PIlkVvvB30LIvTTOnTPrdBV2g+T/2IfFVKSWi17K3dEyrIKSZoHNRz/Ba3kIA1daKxY3A4AnXZ+rcks74G2AMWyN/3E7Q07+eYfR9kcdjX/Qn+j79977zOfOWE/5ZVm9rKurTke+AVAHbPoIejY9SNKb/Ae9EHElsKyr5sfLJtc8bzeRjRUG9CDN0g5zfMEcsPPT1JubnmSI8YlN5osaB7Y3mL3B5JT8hlXBI0d9chmbv7abjtZ1D9YJvHvSdogIv8WUo51Wb4Ba+YWiyc4ej00PfOhuA3EEYRQIDAQAB
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmjBcbgANiqb0D8ioA1IEnvgDrj51S1qh/KqoLGGXG4mRm3MfRDk8iWRW+8HfQsi9NM6dM+t0FXaD5P/Yh8VUpJaLXsrd0TKsgpJmgc1HP8FreQgDV1orFjcDgCddn6tySzvgbYAxbI3/cTtDTv55h9H2Rx2Nf9Cf6Pv33vvM585YT/llWb2sq6tOR74BUAds+gh6Nj1I0pv8B70QcSWwrKvmx8sm1zxvN5GNFQb0IM3SDnN8wRyw89PUm5ueZIjxiU3mixoHtjeYvcHklPyGVcEjR31yGZu/tpuO1nUP1gm8e9J2iAi/xZSjnVZvgFr5haLJzh6PTQ986G4DcQRhFAgMBAAECggEACAlN0COO25g/KPfqyPF4GKKAHt27hKobpU86DKECauS1CDWdEAcLEH2QoWRZvmCVYbnyrQc/L6lt7A5cYmo9EWg3LFtQ+N6o30FcsbOpffQmHlVm/uqESwtlBCqAEgvw1XCr435F+lvYfplFqwIIXXJTtiYTMyfFNLu3Zi347zyFeMsejB7fSi9edr1szgX+jvtRzFXJCJgdewj/D+cEN/LzsBgO5IIxwdYg8jHwN0rzRcB+SXhWdFN/PYW+zZJtEgPm4NwabJSETw+348HvfTuvKUBwHibZjtN7tprPBQ/wLT4vIx3qL4e8t1FplvPKnjvmrOq2lPJ4BBt1GVjqnQKBgQDFpa+MM6ZDqidLOWH1782LSygv4j15QmUwM+EhFQ3LwI6/QdoMGdM9AOY8nWtSmYYVBIOdN1Ughgt+hzOklR5oTqrFz3HtUF8spjrJqaefdWaMhuuCQAo76sT/nM9E9MN/SRc0XelSOSAmx7Ie8v2Vrk6Yq1Dc+IxLym4kLIyqRwKBgQDXt9icCDMB6MMMXwnCWPfY7MABNVniyraJLFqMaP2bX4hsmRRQ+oegoF636bBH2MQaHfJ6ZkoMM1BBMX9fInYwmOH4wz/OfnPCcqz1w+yEDerjNZYiHP9xJLek1q2Jk+UE8w9GPjXZhzfmpiwCTpaynUGxqhhTOigMqDKsvNFjEwKBgAMab+Auq2yijk1jEEOxSTPnsTDXR4nQ3g/csKs5Tmclldgw64CHI0bw7ayD+Dxqxq0rzfk49jA1ipao/smVwc13drz2Xd6RBX2I+qFR9ZzOVhbcw3PfF4oLTJ6K0sJNaYhlGGUtGE2/Md8KAaT0wcCI5RkGj5V4nZNPEV2mCWtfAoGBAJJ1GJR/IJpoPJzWnZqcqtFVk9p+LWPD+4BQY722vpBRoR8SI3ADWDffCc/V0kBFVIbi1DDz58w2voM0puShUhsWgT1S2qxIwDFBiFpnxdm2VUYjqKXKiEd6BVDeC/4/MhtVJoarUAY7PuHS6kg6sSfdiq+j61X+QxiszZLns0WPAoGAOPWFvwFnaMSIYxZHQf/xPymzCJqOdeBkURIOji8B0uRk2cEZtvPyR3/Np5mu6uVLJgqyo3vfbFDLf+CaVQa/hskXiGxoasY6r1zCs8OfAqd0/H4X1xVrERFG5SbJADqHGttnQohGLREuiNOq5exR7cNTgQxpiicQ7USNx4CyF18=

logging:
  level:
    org:
      springframework:
        security:
          oauth2: DEBUG

