server:
  port: 8903

spring:
  application:
    name: hello-spring-security-res-server
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://spring-oauth2-server:8901
logging:
  level:
    org:
      springframework:
        security:
          oauth2: DEBUG

