server:
  port: 8902

spring:
  application:
    name: hello-spring-security-res-server
  security:
    oauth2:
      client:
        provider:
          #认证服务器信息
          oauth2-server:
            #授权地址
            issuer-uri: http://spring-oauth2-server:8901
            authorizationUri: ${spring.security.oauth2.client.provider.oauth2-server.issuer-uri}/oauth2/authorize
            #令牌获取地址
            tokenUri: ${spring.security.oauth2.client.provider.oauth2-server.issuer-uri}/oauth2/token
        registration:
          messaging-client-oidc:
            #认证提供者，标识由哪个认证服务器进行认证，和上面的oauth-server进行关联
            provider: oauth2-server
            #客户端名称
            client-name: web平台
            #客户端id，从认证平台申请的客户端id
            client-id: web-client-id
            #客户端秘钥
            client-secret: secret
            #客户端认证方式
            client-authentication-method: client_secret_basic
            #使用授权码模式获取令牌（token）
            authorization-grant-type: authorization_code
            #回调地址，接收认证服务器回传code的接口地址，之前我们是使用http://www.baidu.com代替
            # 注意：和认证服务器配置的回调地址要一致
            redirect-uri: http://spring-oauth2-client:8902/login/oauth2/code/messaging-client-oidc
            scope:
              - profile
              - openid
logging:
  level:
    org:
      springframework:
        security:
          oauth2: DEBUG

